<a href="https://colab.research.google.com/github/Fiarma5233/Data-Science/blob/master/Data_Input_Output_With_Table_HTML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# On defini d'abord l'url du site qu'on veut extraire les tableau

url = 'https://en.wikipedia.org/wiki/World_population'

In [ ]:
tables = pd.read_html(url)

In [ ]:
# nombre de tableaux html trouves a la page de cette url
len(tables)

In [ ]:
# afficher le  tableau parmis les 30
tables[7]

   Rank                 Country  Population  Area (km2)  Density (pop/km2)
0     1               Singapore     5921231         719               8235
1     2              Bangladesh   165650475      148460               1116
2     3  Palestine[note 3][103]     5223000        6025                867
3     4          Taiwan[note 4]    23580712       35980                655
4     5             South Korea    51844834       99720                520
5     6                 Lebanon     5296814       10400                509
6     7                  Rwanda    13173730       26338                500
7     8                 Burundi    12696478       27830                456
8     9                   India  1389637446     3287263                423
9    10             Netherlands    17400824       41543                419

In [ ]:
# sauvegarde du df en tant qu'un fichier html
tables = tables[7]
tables.to_html('fichier.html', index=False)